<?xml version="1.0"?>

<robot name="tele">
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
    <property name="base_diameter" value="0.455"/>
    <property name="base_lift" value="0.11"/>
    <property name="hukuyo_scan_height" value="0.056"/>

    <macro name="tele">

      <link name="base_link">
      </link>

      <link name="base_footprint">
      </link>

      <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 ${-base_lift}"/>
        <parent  link="base_link"/>
        <child link="base_footprint"/>
      </joint>
      
      <link name="base_laser">
      </link>

      <joint name="base_laser_joint" type="fixed">
        <origin xyz="${base_diameter/2 - 0.029 - 0.025} 0 ${0.056 + 0.018}"/>
        <parent link="base_link"/>
        <child  link="base_laser"/>
      </joint>
    </macro>

    <tele />

</robot>
