<?xml version="1.0"?>

<robot name="mitro">
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159265359"/>
    <property name="base_diameter" value="0.4572"/>
    <property name="base_plate_lift" value="0.112"/> <!-- lift top top of plate -->
    <property name="base_plate_height" value="0.0123"/>
    <property name="top_plate_lift" value="0.121"/> <!-- lift to top of plate -->
    <property name="top_plate_height" value="0.0066"/>
    <property name="hokuyo_scan_height" value="0.056"/>
    <property name="sonar_scan_height" value="0.037"/>
    <property name="pole_length" value="1.45"/>
    <property name="pole_x_offset" value="-0.0611"/>
    <property name="kinect_pitch_angle" value="1.18"/>
    <property name="kinect_roll_angle" value="0.06"/>
    <property name="kinect_yaw_angle" value="0.02"/>

    <macro name="mitro">

      <link name="base_link">
      </link>

      <link name="base_plate">
        <visual>
          <origin xyz="0 0 -${base_plate_height}" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://mitro_description/meshes/base_plate.stl"/>
          </geometry>
	  <material name="wood">
	    <color rgba="0.65 0.5 0.37 1"/>
	  </material>
        </visual>
      </link>

      <joint name="base_plate_joint" type="fixed">
        <origin xyz="0 0 ${base_plate_lift}"/>
        <parent link="base_link"/>
        <child link="base_plate"/>
      </joint>
      
      <link name="base_sonar">
      </link>
      
      <joint name="base_sonar_joint" type="fixed">
        <origin xyz="0 0 ${sonar_scan_height}"/>
        <parent link="base_plate"/>
        <child link="base_sonar"/>
      </joint>

      <link name="base_laser">
	<visual>
	  <origin xyz="0.0 0.0 ${-hokuyo_scan_height}" rpy="${M_PI/2} 0 ${M_PI/2}" />
	  <geometry>
	    <mesh filename="package://mitro_description/meshes/hokuyo_urg.stl"/>
	  </geometry>
	  <material name="dark grey">
	    <color rgba="0.2 0.2 0.2 1"/>
	  </material>
	</visual>
      </link>

      <joint name="base_laser_joint" type="fixed">
        <origin xyz="${base_diameter/2 - 0.030 - 0.025} 0.002 ${hokuyo_scan_height + 0.021}" rpy="0 0 -0.032" />
        <parent link="base_plate"/>
        <child link="base_laser"/>
      </joint>

      <link name="top_plate">
        <visual>
          <origin xyz="0 0 -${top_plate_height}" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://mitro_description/meshes/top_plate.stl"/>
          </geometry>
	  <material name="wood">
	    <color rgba="0.65 0.5 0.37 1"/>
	  </material>
        </visual>
      </link>

      <joint name="top_plate_joint" type="fixed">
        <origin xyz="0 0 ${top_plate_lift}"/>
        <parent link="base_plate"/>
        <child link="top_plate"/>
      </joint>

      <link name="base_pole_link" />
      <joint name="base_pole_joint" type="fixed">
	<origin xyz="${pole_x_offset} 0 0" rpy="0 0 0"/>
	<parent link="base_plate"/>
	<child link="base_pole_link"/>
      </joint>

      <link name="top_pole_link">
        <visual>
          <origin xyz="0 0 -${pole_length/2}" rpy="0 0 0" />
          <geometry>
	    <box size="0.045 0.045 ${pole_length}"/>
          </geometry>
	  <material name="aluminium">
	    <color rgba="0.8 0.8 0.8 1"/>
	  </material>
        </visual>
      </link>

      <joint name="top_pole_joint" type="fixed">
	<origin xyz="0 0 ${pole_length}" rpy="0 0 0"/>
	<parent link="base_pole_link"/>
	<child link="top_pole_link"/>
      </joint>


<!-- kinect -->

      <link name="kinect_model_link">
	<visual>
	  <origin xyz="0 0 0" rpy="0 0 0" />
	  <geometry>
	    <mesh filename="package://mitro_description/meshes/kinect.stl"/>
	  </geometry>
	  <material name="dark grey">
	    <color rgba="0.2 0.2 0.2 1"/>
	  </material>
	</visual>
      </link>

      <joint name="kinect_model_joint" type="fixed">
        <origin xyz="0.10 0 0" rpy="0 ${kinect_pitch_angle} 0"/>
        <parent link="top_pole_link"/>
        <child link="kinect_model_link"/>
      </joint>


      <link name="kinect_link"/>
      <joint name="kinect_joint" type="fixed">
        <origin xyz="0.11 -0.08 0" rpy="${kinect_roll_angle} ${kinect_pitch_angle} ${kinect_yaw_angle}"/> <!-- TODO: requires meassurement -->
        <parent link="top_pole_link"/>
        <child link="kinect_link"/>
      </joint>

      <link name="kinect_depth_frame"/>
      <joint name="kinect_depth_frame_joint" type="fixed">
	<origin xyz="0 0.049 0"/>
	<parent link="kinect_link"/>
	<child link="kinect_depth_frame"/>
      </joint>

      <link name="kinect_rgb_frame"/>
      <joint name="kinect_rgb_frame_joint" type="fixed">
	<origin xyz="0 0.022 0"/>
	<parent link="kinect_link"/>
	<child link="kinect_rgb_frame"/>
      </joint>

      <link name="kinect_depth_optical_frame"/>
      <joint name="kinect_depth_frame_optical_joint" type="fixed">
	<origin xyz="0 0 0" rpy="-${M_PI/2} 0 -${M_PI/2}"/>
	<parent link="kinect_depth_frame"/>
	<child link="kinect_depth_optical_frame"/>
      </joint>

      <link name="kinect_rgb_optical_frame"/>
      <joint name="kinect_rgb_frame_optical_joint" type="fixed">
	<origin xyz="0 0 0" rpy="-${M_PI/2} 0 -${M_PI/2}"/>
	<parent link="kinect_rgb_frame"/>
	<child link="kinect_rgb_optical_frame"/>
      </joint>

    </macro>

    <mitro />

</robot>
