<?xml version="1.0"?>

<robot name="mitro">
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
    <property name="base_diameter" value="0.4572"/>
    <property name="base_lift" value="0.11"/>
    <property name="hokuyo_scan_height" value="0.056"/>

    <macro name="mitro">

      <link name="base_link">
      </link>

      <link name="base_plate">
        <visual>
          <origin xyz="0 0 0.0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://mitro_description/meshes/base_plate.stl"/>
          </geometry>
	  <material name="wood">
	    <color rgba="0.65 0.5 0.37 1"/>
	  </material>
        </visual>
      </link>

      <joint name="base_plate_joint" type="fixed">
        <origin xyz="0 0 ${base_lift}"/>
        <parent link="base_link"/>
        <child link="base_plate"/>
      </joint>

      <link name="base_laser">
	<visual>
	  <origin xyz="0.0 0.0 ${-hokuyo_scan_height}" rpy="${M_PI/2} 0 ${M_PI/2}" />
	  <geometry>
	    <mesh filename="package://mitro_description/meshes/hokuyo_urg.stl"/>
	  </geometry>
	  <material name="dark grey">
	    <color rgba="0.2 0.2 0.2 1"/>
	  </material>
	</visual>
      </link>

      <joint name="base_laser_joint" type="fixed">
        <origin xyz="${base_diameter/2 - 0.030 - 0.025} 0.002 ${hokuyo_scan_height + 0.019}" rpy="0 0 -0.032" />
        <parent link="base_plate"/>
        <child link="base_laser"/>
      </joint>

      <link name="top_plate">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <mesh filename="package://mitro_description/meshes/top_plate.stl"/>
          </geometry>
	  <material name="wood">
	    <color rgba="0.65 0.5 0.37 1"/>
	  </material>
        </visual>
      </link>

      <joint name="top_plate_joint" type="fixed">
        <origin xyz="0 0 0.15"/>
        <parent link="base_plate"/>
        <child link="top_plate"/>
      </joint>


<!-- kinect -->

      <link name="kinect_link">
	<visual>
	  <origin xyz="0 0 0" rpy="0 0 0" />
	  <geometry>
	    <mesh filename="package://mitro_description/meshes/kinect.stl"/>
	  </geometry>
	  <material name="dark grey">
	    <color rgba="0.2 0.2 0.2 1"/>
	  </material>
	</visual>
      </link>

      <joint name="kinect_joint" type="fixed">
        <origin xyz="0 0 1.56" rpy="0 1.16 0"/>
        <parent link="base_link"/>
        <child link="kinect_link"/>
      </joint>

      <link name="kinect_depth_frame"/>
      <joint name="kinect_depth_frame_joint" type="fixed">
	<origin xyz="0 -0.02 0"/>
	<parent link="kinect_link"/>
	<child link="kinect_depth_frame"/>
      </joint>

      <link name="kinect_rgb_frame"/>
      <joint name="kinect_rgb_frame_joint" type="fixed">
	<origin xyz="0 -0.045 0"/>
	<parent link="kinect_link"/>
	<child link="kinect_rgb_frame"/>
      </joint>

      <link name="kinect_depth_optical_frame"/>
      <joint name="kinect_depth_frame_optical_joint" type="fixed">
	<origin xyz="0 0 0" rpy="-${M_PI/2} 0 -${M_PI/2}"/>
	<parent link="kinect_depth_frame"/>
	<child link="kinect_depth_optical_frame"/>
      </joint>

      <link name="kinect_rgb_optical_frame"/>
      <joint name="kinect_rgb_frame_optical_joint" type="fixed">
	<origin xyz="0 0 0" rpy="-${M_PI/2} 0 -${M_PI/2}"/>
	<parent link="kinect_rgb_frame"/>
	<child link="kinect_rgb_optical_frame"/>
      </joint>

    </macro>

    <mitro />

</robot>
