source_topic: cmd_twist_tele
target_topic: cmd_twist_tele_assisted
costmap_topic: move_base/local_costmap/obstacles
sonar_topic: sonar_scan
base_frame_id: base_link
max_range: 1.5 # maximum range for which obstacles will be considered
clearing_dist: 0.15 # minimum distance required between robot base and obstacles
sonar_clearing_dist: 0.3
