# from pr2_teleop/config/
# adapted for mitro

# Axes
axis_vx: 1
axis_vy: 0
axis_vw: 0
axis_pan: 0
axis_tilt: 3

# base velocities
max_vw: 1.0
max_vx: 0.5
max_vy: 0.0
max_vw_run: 2.0
max_vx_run: 1.0
max_vy_run: 0.0

# Buttons have changed for PS3 controller mapping 
# With joystick remapper, this works with all joysticks on "/joy" 
run_button: 11
torso_dn_button: 14
torso_up_button: 12
head_button: 8
deadman_button: 10
