wheel_base: 0.393 # check this again
wheel_radius: 0.075286 # check this again
ticks_per_revolution: 3200
base_diameter: 0.4572

#hardware related stuff
#arduino_port: /dev/ttyUSB0 #set in mitro_base_controller launch file
wifi: wlan0
hostname_base: mitro  # was bob
# hostname_laptop: mitro-laptop
