wheel_base: 0.394 #0.393
wheel_radius: 0.075286 #0.07475
ticks_per_revolution: 3200 #36
base_diameter: 0.4572

#hardware related stuff
#arduino_port: /dev/ttyUSB0 #set in mitro_base_controller launch file
wifi: wlan0
hostname_base: bob
hostname_laptop: mitro-laptop
