TrajectoryPlannerROS:
    max_vel_x: 0.3
    min_vel_x: 0.05
    max_rotational_vel: 0.75
    min_in_place_rotational_vel: 0.5
    acc_lim_th: 2.0
    acc_lim_x: 4
    acc_lim_y: 0.0
    holonomic_robot: false 
