TrajectoryPlannerROS:
    max_vel_x: 0.3
    min_vel_x: 0.15
    max_vel_theta: 0.75
    min_vel_theta: 0.0
    min_in_place_vel_theta: 1.25
    acc_lim_theta: 2.0
    acc_lim_x: 4.0
    acc_lim_y: 0.0
    holonomic_robot: false
