TrajectoryPlannerROS:
    max_vel_x: 0.5
    min_vel_x: 0.3
    max_vel_theta: 1.25
    min_in_place_vel_theta: 1.25
    min_in_place_rotational_vel: 1.25
    acc_lim_theta: 1.5
    acc_lim_x: 0.5
    acc_lim_y: 0.0
    holonomic_robot: false

    yaw_goal_tolerance: 0.25
    xy_goal_tolerance: 0.2
    latch_xy_goal_tolerance: true

NavfnROS:
    default_tolerance: 0.3