TrajectoryPlannerROS:
    max_vel_x: 0.5
    min_vel_x: 0.2
    max_rotational_vel: 1.0
    min_in_place_rotational_vel: 0.3 #0.5
    acc_lim_th: 1.4 #1.0
    acc_lim_x: 0.625 #0.7
    acc_lim_y: 0.0
    holonomic_robot: false 
