obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.225
inflation_radius: 0.225

transform_tolerance: 0.5
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: base_scan, marking: true, clearing: true, obstacle_range: 3.0, raytrace_range: 5.0}
