obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.225
inflation_radius: 0.225

transform_tolerance: 1.0
observation_sources: point_cloud_sensor point_cloud_sensor2

#laser_scan_sensor: {sensor_frame: base_laser, data_type: LaserScan, topic: base_scan, marking: true, clearing: true, obstacle_range: 3.0, raytrace_range: 5.0}

point_cloud_sensor: {sensor_frame: /kinect_depth_optical_frame, data_type: PointCloud2, topic: /cloud_obstacles, marking: true, clearing: false, obstacle_range: 2.15, raytrace_range: 3.0}

point_cloud_sensor2: {sensor_frame: /kinect_depth_optical_frame, data_type: PointCloud2, topic: /cloud_voxel, marking: false, clearing: true, obstacle_range: 3.0, raytrace_range: 3.0}
